module Billing

  def self.request_body(session)  
    return "<?xml version='1.0' encoding='utf-8'?> 
            <methodCall>
              <methodName>
                UpdateBalanceAndDate
              </methodName>
              <params>
                <param>
                  <value>
                    <struct>
                      <member>
                        <name>
                          originNodeType
                        </name>
                        <value>
                          <string>
                            EXT
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          originHostName
                        </name>
                        <value>
                          <string>
                            NGSER
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          originTransactionID
                        </name>
                        <value>
                          <string>
                            #{session.session_id}
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          originTimeStamp
                        </name>
                        <value>
                          <dateTime.iso8601>
                            #{Time.now.iso8601}
                          </dateTime.iso8601>
                        </value>
                      </member>
                      <member>
                        <name>
                          subscriberNumber
                        </name>
                        <value>
                          <string>
                            #{session.msisdn}
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          transactionCurrency
                        </name>
                        <value>
                          <string>
                            XOF
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          adjustmentAmountRelative
                        </name>
                        <value>
                          <string>
                            -#{session.subscription.price}
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          transactionCode
                        </name>
                        <value>
                          <string>
                            11
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          transactionType
                        </name>
                        <value>
                          <string>
                            MoovRevision
                          </string>
                        </value>
                      </member>
                    </struct>
                  </value>   
                </param>
              </params>
            </methodCall>"
  end

  def self.response_body
    return "<?xml version='1.0' encoding='utf-8'?>
            <methodResponse>
              <params>
                <param>
                  <value>
                    <struct>
                      <member>
                        <name>
                          accountFlagsAfter
                        </name>
                        <value>
                          <struct>
                            <member>
                              <name>
                                activationStatusFlag
                              </name>
                              <value>
                                <boolean>
                                  1
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                negativeBarringStatusFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                serviceFeePeriodExpiryFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                serviceFeePeriodWarningActiveFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                supervisionPeriodExpiryFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                supervisionPeriodWarningActiveFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                          </struct>
                        </value>
                      </member>         
                      <member>
                        <name>
                          accountFlagsBefore
                        </name>
                        <value>
                          <struct>
                            <member>
                              <name>
                                activationStatusFlag
                              </name>
                              <value>
                                <boolean>
                                  1
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                negativeBarringStatusFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                serviceFeePeriodExpiryFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                serviceFeePeriodWarningActiveFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                supervisionPeriodExpiryFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                            <member>
                              <name>
                                supervisionPeriodWarningActiveFlag
                              </name>
                              <value>
                                <boolean>
                                  0
                                </boolean>
                              </value>
                            </member>
                          </struct>
                        </value>
                      </member>
                      <member>
                        <name>
                          accountValue1
                        </name>
                        <value>
                          <string>
                            3597
                          </string>
                        </value>
                      </member>                         
                      <member>
                        <name>
                          currency1
                        </name>
                        <value>
                          <string>
                            XOF
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          originTransactionID
                        </name>
                        <value>
                          <string>
                            30706
                          </string>
                        </value>
                      </member>
                      <member>
                        <name>
                          responseCode
                        </name>
                        <value>
                          <i4>
                            0
                          </i4>
                        </value>                 
                      </member>
                    </struct>
                  </value>
                </param>
              </params>
            </methodResponse>"
  end
  
end
